// Generated by CoffeeScript 1.9.3
(function() {
  var jfd, json;

  jfd = require('jsonflow-asciidump');

  json = require(__dirname + "/graph.coffee");

  console.log(jfd.render(json));

}).call(this);
