// Generated by CoffeeScript 1.9.3
(function() {
  var jref, undirender;

  undirender = require('undirender');

  jref = require('json-ref-lite');

  module.exports = (function(me, opts) {
    me.render = function(json) {
      var graph, i, k, len, name, node, nodes, o, ref, s, space;
      graph = [];
      json = jref.resolve(json);
      for (name in json) {
        node = json[name];
        json[name].name = name;
      }
      for (k in json) {
        node = json[k];
        if (node.output != null) {
          ref = node.output;
          for (i = 0, len = ref.length; i < len; i++) {
            o = ref[i];
            graph.push([node.name, o.name]);
          }
        }
      }
      nodes = graph.length;
      space = ((opts != null ? opts.space : void 0) ? opts.space : 2);
      s = undirender(nodes * space, parseInt((nodes / 2) * space), graph);
      return s;
    };
    return me;
  })({});

}).call(this);
